# -*- coding: utf-8 -*-
"""Lista na dimensão de n elementos entre 0 e 99

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMR559UTlnlBAsWslMeu11rbqLBggjic
"""

import random 

valores_aleatorios = []
primeiro_quadril = []
segundo_quadril = []
terceiro_quadril = []
quarto_quadril = []


n = int (input("Digite qualquer número:"))
def linha():
  print("_"*70)
for i in range(0,n):
    z = random.randint(0,99)
    if (0 <= z <= 24):
        primeiro_quadril.append(z)
    elif (25 <= z <= 49):
        segundo_quadril.append(z)
    elif (50 <= z <= 74):
        terceiro_quadril.append(z)
    elif (75 <= z <= 99):
        quarto_quadril.append(z)
        
    valores_aleatorios.append(z)
  

print(valores_aleatorios)
linha()
print("Elementos do 1º quadril:", len(primeiro_quadril))
print("Elementos do 2º quadril:", len(segundo_quadril))
print("Elementos do 3º quadril:", len(terceiro_quadril))
print("Elementos do 4º quadril:", len(quarto_quadril))